### ISSUE TITLE
Option to Hide Initial Plugin Message [Feature Request] 

### ISSUE THREAD

**Issue by gmoqa** [didalgolab/chatgpt-intellij-plugin#1]
I loved the plugin, it's very well integrated into the IDE and performs quite well. After reviewing its options, I only miss one feature: the ability to hide the message that appears at the beginning, indicating what you can do. It would be great to have the option to hide it or show it only once.

Saludos

**Comment by didalgolab** [comment]
Thank you for your feedback. I will include such feature in the next release.

**Comment by didalgolab** [comment]
Implemented in v0.2.8 (pending approval in Marketplace)
