### ISSUE TITLE
Google OAuth not working 

### ISSUE THREAD

**Issue by titidutarn** [didalgolab/chatgpt-intellij-plugin#19]
Couldn’t sign you in
This browser or app may not be secure. [Learn more](https://support.google.com/accounts/answer/7675428?hl=en-US)
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.

**Comment by didalgolab** [comment]
It cannot be fixed. Please read this comment: https://github.com/didalgolab/chatgpt-intellij-plugin/issues/5#issuecomment-1692263268

**Comment by didalgolab** [comment]
Duplicate of #5
