### ISSUE TITLE
Pasting stops working

### ISSUE THREAD

**Issue by oysteinkrog** [didalgolab/chatgpt-intellij-plugin#23]
I installed the latest beta release (as gpt4o is much nicer due to speed), but now pasting does not work.
Fixed by disabling.

**Comment by didalgolab** [comment]
@oysteinkrog Thanks for the feedback. Can you share a little more information?

Are you sure you have version v1.0.0 installed - because it is still in the pending approval on the marketplace, unless you installed it from the package from GitHub? What IDE type and version are you using? What exactly stopped working for you?

**Comment by oysteinkrog** [comment]
@didalgolab I installed the package from the releases page here in github ("ChatGPT.Integration-1.0.0-231-signed.zip").
I am using: 

> JetBrains Rider 2024.1.1
Build #RD-241.14494.325, built on April 16, 2024
Licensed to Initial Force / Øystein Krog
Subscription is active until March 19, 2025.
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
.NET Core v8.0.1 x64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 32
Registry:
  ide.tooltip.initialDelay.highlighter=0
  ide.experimental.ui=true
  ide.new.project.model.index.case.sensitivity=true
Non-Bundled Plugins:
  com.intellij.resharper.HeapAllocationsViewer (2024.1.0)
  Key Promoter X (2024.1.0)
  Abc.MoqComplete.Rider (2024.1.1.1)
  com.settler.rider.specflow (1.23.6)
  GrepConsole (13.0.2-IJ2023.3)
  IdeaVIM (2.12.0)
  io.wisetime.plugins.window.branch (2.0.0)
  com.ppolivka.plugin.gitcleaner (1.1.4)

**Comment by didalgolab** [comment]
Fixed in v1.0.1

**Comment by oysteinkrog** [comment]
Confirmed fixed, thank you :)
