### ISSUE TITLE
ChatGPT encountered an error when using the custom API, resulting in a "Failed to json" message.

### ISSUE THREAD

**Issue by jixishi** [didalgolab/chatgpt-intellij-plugin#25]
Version: 1.0.1-231
The previous version 0.2.12-231 was working fine.
![image](https://github.com/didalgolab/chatgpt-intellij-plugin/assets/57534147/dced2063-358f-4c21-861b-3c94c4902c92)
![image](https://github.com/didalgolab/chatgpt-intellij-plugin/assets/57534147/9460d30d-87e0-4187-805e-2bcc0ddff0c6)

**Comment by didalgolab** [comment]
It's unfortunate, but the interpretation of custom server addresses indeed changed between versions. In v0.2.12, a full URL like `https://api.openai.com/v1/chat/completions` was required. However, in v1.0.1, only the base URL (e.g., `https://api.openai.com/`) is needed, as the path (`v1/chat/completions`) is added automatically.

However, the error message displayed is strange enough that I'm not convinced it's solely a connection issue. It's possible the API returns a response that the plugin can't parse.

Questions:
1. What was your custom server address in v0.2.12? I suspect it wasn't just `https://api.nextapi.fun`, correct?
2. Is the API endpoint api.nextapi.fun publicly accessible for testing purposes?

**Comment by didalgolab** [comment]
@jixishi, have you had the opportunity to look over my questions?

**Comment by jixishi** [comment]
@didalgolab    In the old version 0.2.12, it was https://api.nextapi.fun/v1/chat/completions. In the new version 1.0.1, when adding /v1/chat/completions at the end, it will throw an error indicating duplicate removal, then display the error message with the image.

**Comment by jixishi** [comment]
Using the same proxy address in other programs is fine, I suspect there may be an issue with the JSON parsing that is not extracting the information correctly.

**Comment by didalgolab** [comment]
@jixishi Please attach the full IDEA log for the period when the chat error occurred.

**Comment by jixishi** [comment]
Hi, how do I go about getting the log files?

**Comment by didalgolab** [comment]
https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

**Comment by jixishi** [comment]
Just updated the plugin and everything seems to be working fine now
![image](https://github.com/user-attachments/assets/e27c9ac3-80e7-4f5b-9964-ae5942909c06)
