### ISSUE TITLE
Log In with Google

### ISSUE THREAD

**Issue by AndrewMarkUK** [didalgolab/chatgpt-intellij-plugin#5]
When I try to login with Google, to the Online ChatGPT, which was my original method of authentication, I get this:

"Couldn’t sign you in
This browser or app may not be secure. [Learn more](https://support.google.com/accounts/answer/7675428?hl=en)
Try using a different browser. If you’re already using a supported browser, you can try again to sign in."

I do have a paid account ChatGPT Plus.

Is there something more I need to do?

I am trying to use this within JetBrains PHPStorm -Latest. Windows 10. Also, to be certain the login is OK. I went directly to the (Chat) site to log in, using the same details, and it logs in fine.

**Comment by didalgolab** [comment]
Unfortunately, Google doesn't support login authentication through embedded browsers, and there's nothing I can do about it. A possible solution is to create a new ChatGPT account with password authentication (but keep in mind that OpenAI allows only two accounts to be associated with the same mobile phone number) and use that account from within the IDE plugin.

However, I want to emphasize that the preferred way to use the plugin is through API access with the "GPT-3.5-Turbo" or "GPT-4" tabs. This is where most of the plugin development and its features are focused. "Online ChatGPT" provides only a simple rudimentary embedded browser with access to the ChatGPT Pro account and no other IDE integrations.

So, my suggestion is to try using API access instead.

**Comment by rakim013** [comment]
If the option does not work then the plugin should not give users the option to login via google. Gives a false sense of features. Also I prefer to use the online version instead of the api because that is free and the api is not.

**Comment by didalgolab** [comment]
@rakim013 Login inside the online tab definitely works for accounts with password-only authentication (I've just tested it). However, using ChatGPT within such a narrow window isn't a pretty experience – as I mentioned before: it's essentially just an embedded browser. Thank you for the feedback. I am considering removing this option from the plugin entirely.

**Comment by rakim013** [comment]
Thanks for the quick response. My account has password-only authentication, in this case it does not have 2fa configured. What else can be going wrong & why is it not working I wonder?

**Comment by didalgolab** [comment]
That's strange. What error are you getting?
